laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('produtos', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/busca', 'ProdutosController@busca')->name('produtos.busca');
    Route::get('produtos/{produto}', 'ProdutosController@show')->name('produtos.show');
    Route::get('veiculos/{marca}', 'ProdutosController@veiculos')->name('produtos.veiculos');
    Route::get('equipe', 'EquipeController@index')->name('equipe');
    Route::get('assistencia-tecnica', 'AssistenciaTecnicaController@index')->name('assistencia-tecnica');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('catalogo', 'CatalogoController');
		Route::resource('veiculo', 'VeiculoController');
		Route::resource('marca', 'MarcaController');
		Route::resource('linha', 'LinhaController');
		Route::resource('categoria', 'CategoriaController');
		Route::resource('produtos-apresentacao', 'ProdutosApresentacaoController', ['only' => ['index', 'update']]);
		Route::resource('catalogos', 'CatalogosController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
		Route::resource('equipe-texto', 'EquipeTextoController', ['only' => ['index', 'update']]);
		Route::resource('equipe', 'EquipeController');
		Route::resource('assistencia-tecnica', 'AssistenciaTecnicaController', ['only' => ['index', 'update']]);
		Route::resource('tecnicos', 'TecnicosController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AssistenciaTecnicaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AssistenciaTecnicaRequest;
use App\Http\Controllers\Controller;

use App\Models\AssistenciaTecnica;

class AssistenciaTecnicaController extends Controller
{
    public function index()
    {
        $registro = AssistenciaTecnica::first();

        return view('painel.assistencia-tecnica.edit', compact('registro'));
    }

    public function update(AssistenciaTecnicaRequest $request, AssistenciaTecnica $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = AssistenciaTecnica::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.assistencia-tecnica.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CatalogoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CatalogoRequest;
use App\Http\Controllers\Controller;

use App\Models\Produto;
use App\Models\Marca;
use App\Models\Categoria;
use App\Models\Veiculo;

class CatalogoController extends Controller
{
    public function index()
    {
        $registros = Produto::paginate(20);

        return view('painel.catalogo.index', compact('registros'));
    }

    public function create()
    {
        $categorias = Categoria::lists('descricao', 'id');
        $marcas     = Marca::lists('descricao', 'id');
        $veiculos   = [];

        return view('painel.catalogo.create', compact('categorias', 'marcas', 'veiculos'));
    }

    public function store(CatalogoRequest $request)
    {
        try {

            $input = $request->except('categoria', 'veiculo');

            if (! $request->has('id_marca')) {
                $input['id_marca'] = null;
            }

            if (isset($input['foto1'])) $input['foto1'] = Produto::upload_foto_1();

            if (isset($input['foto2'])) $input['foto2'] = Produto::upload_foto_2();

            $registro = Produto::create($input);

            $categoria = ($request->get('categoria') ?: []);
            $registro->categoria()->sync($categoria);

            $veiculo = ($request->get('veiculo') ?: []);
            $registro->veiculo()->sync($veiculo);

            return redirect()->route('painel.catalogo.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Produto $registro)
    {
        $categorias = Categoria::lists('descricao', 'id');
        $marcas     = Marca::lists('descricao', 'id');
        $veiculos   = Veiculo::where('id_marca', $registro->id_marca)->lists('descricao', 'id');

        return view('painel.catalogo.edit', compact('registro', 'categorias', 'marcas', 'veiculos'));
    }

    public function update(CatalogoRequest $request, Produto $registro)
    {
        try {

            $input = $request->except('categoria', 'veiculo');

            if (! $request->has('id_marca')) {
                $input['id_marca'] = null;
            }

            if (isset($input['foto1'])) $input['foto1'] = Produto::upload_foto_1();

            if (isset($input['foto2'])) $input['foto2'] = Produto::upload_foto_2();

            $registro->update($input);

            $categoria = ($request->get('categoria') ?: []);
            $registro->categoria()->sync($categoria);

            $veiculo = ($request->get('veiculo') ?: []);
            $registro->veiculo()->sync($veiculo);

            return redirect()->route('painel.catalogo.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Produto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.catalogo.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CatalogosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CatalogosRequest;
use App\Http\Controllers\Controller;

use App\Models\Catalogos;

use App\Helpers\Tools;

class CatalogosController extends Controller
{
    public function index()
    {
        $registro = Catalogos::first();

        return view('painel.catalogos.edit', compact('registro'));
    }

    public function update(CatalogosRequest $request, Catalogos $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_tensionadores_e_polias'])) $input['imagem_tensionadores_e_polias'] = Catalogos::upload_imagem_tensionadores_e_polias();
            if (isset($input['imagem_kits_de_distribuicao'])) $input['imagem_kits_de_distribuicao'] = Catalogos::upload_imagem_kits_de_distribuicao();

            if ($request->hasFile('arquivo_tensionadores_e_polias')) $input['arquivo_tensionadores_e_polias'] = Tools::fileUpload('arquivo_tensionadores_e_polias');
            if ($request->hasFile('arquivo_kits_de_distribuicao')) $input['arquivo_kits_de_distribuicao'] = Tools::fileUpload('arquivo_kits_de_distribuicao');
            if ($request->hasFile('arquivo_banners')) $input['arquivo_banners'] = Tools::fileUpload('arquivo_banners');

            $registro->update($input);

            return redirect()->route('painel.catalogos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CategoriaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CategoriaRequest;
use App\Http\Controllers\Controller;

use App\Models\Categoria;

class CategoriaController extends Controller
{
    public function index()
    {
        $registros = Categoria::get();

        return view('painel.categoria.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.categoria.create');
    }

    public function store(CategoriaRequest $request)
    {
        try {

            $input = $request->all();

            Categoria::create($input);

            return redirect()->route('painel.categoria.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Categoria $registro)
    {
        return view('painel.categoria.edit', compact('registro'));
    }

    public function update(CategoriaRequest $request, Categoria $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.categoria.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Categoria $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.categoria.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Empresa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>
	<li @if(Tools::routeIs('painel.catalogos*')) class="active" @endif>
		<a href="{{ route('painel.catalogos.index') }}">Catálogos</a>
	</li>
    <li @if(Tools::routeIs('painel.empresa*')) class="active" @endif>
        <a href="{{ route('painel.empresa.index') }}">Empresa</a>
    </li>
    <li class="dropdown @if(Tools::routeIs(['painel.produtos*', 'painel.catalogo.*', 'painel.categoria*', 'painel.linha*', 'painel.marca*', 'painel.veiculo*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Produtos
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.produtos-apresentacao*')) class="active" @endif>
                <a href="{{ route('painel.produtos-apresentacao.index') }}">Apresentação</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.catalogo.*')) class="active" @endif>
                <a href="{{ route('painel.catalogo.index') }}">Catálogo</a>
            </li>
            <li @if(Tools::routeIs('painel.categoria*')) class="active" @endif>
                <a href="{{ route('painel.categoria.index') }}">Categoria</a>
            </li>
            <li @if(Tools::routeIs('painel.linha*')) class="active" @endif>
                <a href="{{ route('painel.linha.index') }}">Linha</a>
            </li>
            <li @if(Tools::routeIs('painel.marca*')) class="active" @endif>
                <a href="{{ route('painel.marca.index') }}">Marca</a>
            </li>
            <li @if(Tools::routeIs('painel.veiculo*')) class="active" @endif>
                <a href="{{ route('painel.veiculo.index') }}">Veículo</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs(['painel.equipe*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Equipe
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.equipe-texto*')) class="active" @endif>
                <a href="{{ route('painel.equipe-texto.index') }}">Texto</a>
            </li>
            <li @if(Tools::routeIs('painel.equipe.*')) class="active" @endif>
                <a href="{{ route('painel.equipe.index') }}">Equipe</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs(['painel.assistencia-tecnica*', 'painel.tecnicos*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Assistência Técnica
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.assistencia-tecnica*')) class="active" @endif>
                <a href="{{ route('painel.assistencia-tecnica.index') }}">Assistência Técnica</a>
            </li>
            <li @if(Tools::routeIs('painel.tecnicos*')) class="active" @endif>
                <a href="{{ route('painel.tecnicos.index') }}">Técnicos</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs('painel.contato*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>